# Generated by Django 2.0.6 on 2018-07-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wise_saying', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_password',
            new_name='password',
        ),
    ]
