# Generated by Django 2.0.6 on 2018-07-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wise_saying', '0002_auto_20180701_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
