# Generated by Django 2.0.6 on 2018-07-01 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wise_saying', '0003_auto_20180701_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saying',
            name='member',
        ),
        migrations.AddField(
            model_name='saying',
            name='writer_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
