# Generated by Django 2.0.6 on 2018-07-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wise_saying', '0005_auto_20180701_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saying',
            old_name='writer_id',
            new_name='writer',
        ),
    ]
