# Generated by Django 2.0.6 on 2018-07-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wise_saying', '0006_auto_20180701_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saying',
            name='contents',
            field=models.CharField(max_length=45),
        ),
    ]
